version: '3.8'
services:
  desktop:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/
      - TITLE=DevContainer Desktop
    shm_size: "1gb"
    volumes:
      - ../:/config/workspace:cached